name: Bug Report
description: Report broken functionality of the swizzin toolset
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting bugs to us. Please make sure you've ran `box update` before, and that you checked that your issue is not covered in the [Documentation](https://swizzin.ltd)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: |
        Steps to reproduce:
        1. Install package '...'
        2. Go to '....'
        3. Error '...'
        Expected results:
    validations:
      required: true
 - type: textarea
    id: logs
    attributes:
      label: Relevant logs and output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: plaintext
